
const CG_BASE="https://api.coingecko.com/api/v3";
const CMC_BASE="https://pro-api.coinmarketcap.com/v1";
const DEX_BASE="https://api.dexscreener.com/latest/dex";
const TERMS={auto:["ai","rwa","defi","depin","gaming","infrastructure","yield","bridge","rpc","agent","network"],ai:["ai","agent","gpu","compute","data","inference","render","virtual"],rwa:["rwa","real world assets","tokenized","treasury","credit","yield","ondo","asset"],depin:["depin","node","storage","compute","network","infrastructure"],gaming:["gaming","gamefi","game","play","nft","esports","guild"],infra:["oracle","storage","infrastructure","data","index","bridge","security","node","rpc","api","network"],defi:["defi","dex","yield","liquidity","swap","lending","staking","perp","vault"],l2:["layer2","layer 2","modular","rollup","zk","optimism","arbitrum","starknet","mantle","base"],meme:["meme","inu","dog","cat","frog","pepe","bonk","wif"]};
const CHAIN={ethereum:"ethereum",solana:"solana",base:"base",bsc:"bsc",arbitrum:"arbitrum",polygon:"polygon",avalanche:"avalanche",optimism:"optimism"};
function norm(x){return String(x||"").toLowerCase().replace(/[^a-z0-9]/g,"")}function num(x){x=Number(x||0);return Number.isFinite(x)?x:0}
function isMajor(c){const s=norm(c.symbol),n=norm(c.name);return ["btc","bitcoin","wbtc","eth","ethereum","weth","bnb","sol","solana","xrp","usdc","usdt","dai"].includes(s)||["bitcoin","ethereum","wrappedbitcoin","wrappedether","solana","tether","usdcoin"].includes(n)}
function risks(c){const cap=num(c.market_cap||c.fdv),vol=num(c.total_volume),liq=num(c.liquidity),ch=Math.abs(num(c.price_change_percentage_24h));const r=[];if(liq&&liq<5000)r.push("низкая ликвидность");if(vol<5000)r.push("слабый объём");if(cap&&cap<100000)r.push("микро-капитализация");if(ch>80)r.push("сильная волатильность");if(isMajor(c))r.push("слишком крупная монета");return r}
function narrative(c,sector){const t=(c.name+" "+c.symbol+" "+(c.description||"")+" "+(c.url||"")).toLowerCase();if(/ai|agent|gpu|compute|data|render|virtual/.test(t))return"AI";if(/rwa|real|treasury|yield|credit|ondo|asset/.test(t))return"RWA";if(/game|gaming|play|nft|esport|guild/.test(t))return"Gaming";if(/depin|node|storage|oracle|rpc|bridge|network|infra/.test(t))return"Infrastructure";if(/swap|dex|yield|lend|stake|vault|perp/.test(t))return"DeFi";if(/inu|dog|cat|pepe|meme|bonk|wif/.test(t))return"Meme";return sector==="auto"?"General":sector.toUpperCase()}
function score(c,risk){let sc=30;const cap=num(c.market_cap||c.fdv),vol=num(c.total_volume),liq=num(c.liquidity),ch=num(c.price_change_percentage_24h),vr=cap?vol/cap:0;if(cap>=1e5&&cap<1e6)sc+=10;if(cap>=1e6&&cap<=1e8)sc+=18;if(cap>5e8)sc-=10;if(cap>1e9)sc-=18;if(vol>=1e4)sc+=6;if(vol>=1e5)sc+=8;if(vol>=1e6)sc+=8;if(liq>=1e4)sc+=6;if(liq>=5e4)sc+=8;if(liq>=2.5e5)sc+=8;if(vr>=.005&&vr<=.5)sc+=9;if(ch>3&&ch<45)sc+=8;if(ch<0&&ch>-25)sc+=4;if(ch>80)sc-=12;if(isMajor(c))sc-=25;sc-=risks(c).length*4;if(risk==="conservative")sc-=risks(c).length*3;if(risk==="aggressive")sc+=5;if(c._source==="CoinMarketCap"&&num(c.liquidity)>0)sc+=2;if(c._source==="CoinGecko"&&num(c.liquidity)>0)sc+=2;return Math.max(1,Math.min(99,Math.round(sc)))}
function budgetOk(c,b){return !b||b==="any"||num(c.current_price)<=Number(b)}function qualityOk(c,r){
  const liq=num(c.liquidity), vol=num(c.total_volume);
  if(c._source!=="DexScreener" && liq===0) return false;
  if(r==="aggressive") return liq>=3000 && vol>=1000;
  if(r==="conservative") return liq>=25000 && vol>=25000;
  return liq>=10000 && vol>=3000;
}
function sectorOk(c,sector){if(sector==="auto")return true;const t=(c.name+" "+c.symbol+" "+(c.description||"")+" "+(c.categories||[]).join(" ")).toLowerCase();return (TERMS[sector]||[]).some(x=>t.includes(x))}
function dedupe(list){const m=new Map();for(const c of list){const k=norm(c.symbol)+":"+norm(c.name);const old=m.get(k);const w=num(c.liquidity)*3+num(c.total_volume)+num(c.market_cap||c.fdv)/300+(c._source==="CoinMarketCap"?50000:0)+(c._source==="CoinGecko"?30000:0);const ow=old?num(old.liquidity)*3+num(old.total_volume)+num(old.market_cap||old.fdv)/300+(old._source==="CoinMarketCap"?50000:0)+(old._source==="CoinGecko"?30000:0):-1;if(!old||w>ow)m.set(k,c)}return[...m.values()]}
async function fetchCoinGecko(){const out=[];try{const r=await fetch(`${CG_BASE}/coins/markets?vs_currency=usd&order=volume_desc&per_page=250&page=1&sparkline=false&price_change_percentage=24h,7d,30d`,{headers:{accept:"application/json"}});if(!r.ok)return out;const arr=await r.json();for(const x of arr)out.push({id:x.id,name:x.name,symbol:x.symbol,image:x.image,current_price:x.current_price,market_cap:x.market_cap,fdv:x.fully_diluted_valuation,total_volume:x.total_volume,price_change_percentage_24h:x.price_change_percentage_24h,price_change_percentage_7d:x.price_change_percentage_7d_in_currency,price_change_percentage_30d:x.price_change_percentage_30d_in_currency,liquidity:0,age_days:0,_source:"CoinGecko",_dexChain:"market",dex:"market",url:`https://www.coingecko.com/en/coins/${x.id}`})}catch(e){}return out}
async function fetchCMC(){const out=[];const key=process.env.CMC_API_KEY;if(!key)return out;try{const r=await fetch(`${CMC_BASE}/cryptocurrency/listings/latest?limit=500&convert=USD`,{headers:{"X-CMC_PRO_API_KEY":key}});if(!r.ok)return out;const j=await r.json();for(const x of j.data||[]){const q=x.quote?.USD||{};out.push({id:String(x.id),name:x.name,symbol:x.symbol,current_price:q.price,market_cap:q.market_cap,fdv:q.fully_diluted_market_cap,total_volume:q.volume_24h,price_change_percentage_24h:q.percent_change_24h,price_change_percentage_7d:q.percent_change_7d,price_change_percentage_30d:q.percent_change_30d,liquidity:0,age_days:0,_source:"CoinMarketCap",_dexChain:"market",dex:"market",url:`https://coinmarketcap.com/currencies/${String(x.slug||x.name).toLowerCase().replaceAll(" ","-")}/`})}}catch(e){}return out}
async function fetchDex(chains,sector,risk){const out=[];const terms=(TERMS[sector]||TERMS.auto).slice(0,risk==="aggressive"?10:6);for(const chain of chains){for(const q of terms){try{const r=await fetch(`${DEX_BASE}/search?q=${encodeURIComponent(chain==="auto"?q:chain+" "+q)}`);if(!r.ok)continue;const j=await r.json();for(const p of j.pairs||[]){if(chain!=="auto"&&String(p.chainId).toLowerCase()!==CHAIN[chain])continue;out.push({id:String(p.chainId)+"-"+String(p.pairAddress),name:p.baseToken?.name||"Unknown",symbol:p.baseToken?.symbol||"?",image:p.info?.imageUrl||"",current_price:num(p.priceUsd),market_cap:num(p.marketCap),fdv:num(p.fdv),total_volume:num(p.volume?.h24),price_change_percentage_24h:num(p.priceChange?.h24),liquidity:num(p.liquidity?.usd),age_days:p.pairCreatedAt?Math.floor((Date.now()-p.pairCreatedAt)/86400000):0,_source:"DexScreener",_dexChain:String(p.chainId).toLowerCase(),dex:p.dexId||"",pair:p.pairAddress||"",tokenAddress:p.baseToken?.address||"",url:p.url||"",website:(p.info?.websites&&p.info.websites[0]?.url)||""})}}catch(e){}}}return out}
export default async function handler(req,res){res.setHeader("Access-Control-Allow-Origin","*");try{const sector=String(req.query.sector||"auto"),risk=String(req.query.risk||"balanced"),budget=String(req.query.budget||"any"),chains=String(req.query.chains||"auto").split(",").filter(Boolean);const [cg,cmc,dex]=await Promise.all([fetchCoinGecko(),fetchCMC(),fetchDex(chains,sector,risk)]);const cgMap=new Map(cg.map(x=>[norm(x.symbol)+":"+norm(x.name),x]));
for(const d of dex){const e=cgMap.get(norm(d.symbol)+":"+norm(d.name));if(e){d.image=d.image||e.image;d.market_cap=d.market_cap||e.market_cap;d.fdv=d.fdv||e.fdv;d.price_change_percentage_7d=e.price_change_percentage_7d;d.price_change_percentage_30d=e.price_change_percentage_30d;}}
const processedRaw=cmc.length+cg.length+dex.length;
let list=dedupe([...dex]).filter(c=>budgetOk(c,budget)).filter(c=>qualityOk(c,risk)).filter(c=>sectorOk(c,sector)||risk==="aggressive");list.forEach(c=>{c._narrative=narrative(c,sector);c._score=score(c,risk);c.risks=risks(c)});list=list.sort((a,b)=>b._score-a._score).slice(0,80);const sources=[];if(cmc.length)sources.push("CoinMarketCap");if(cg.length)sources.push("CoinGecko");if(dex.length)sources.push("DexScreener");res.status(200).json({ok:true,sources,items:list,count:list.length,processed:processedRaw})}catch(e){res.status(500).json({ok:false,error:String(e.message||e)})}}
