const TERMS={ai:["ai","agent","artificial intelligence","depin","compute","gpu","data","machine learning","inference","render","akash","aethir","nosana","grass"],rwa:["rwa","real world assets","tokenized","treasury","credit","yield","ondo","mantra","maple","centrifuge"],meme:["meme","memecoin","inu","dog","cat","frog","pepe","bonk","wif","brett"],defi:["defi","dex","yield","liquidity","swap","lending","staking","perp","vault","aerodrome","jupiter"],gaming:["gamefi","gaming","game","play to earn","p2e","metaverse","nft game","guild","ronin","immutable","gala","illuvium"],infra:["oracle","storage","infrastructure","data","index","bridge","security","node","rpc","pyth","chainlink"],l2:["layer2","layer 2","modular","rollup","zk","optimism","arbitrum","starknet","mantle"],auto:["ai","rwa","gamefi","defi","meme","depin","infrastructure"]};
function flagsFor(p,sector,quality){const s=String(p.baseToken?.symbol||"").toLowerCase(),n=String(p.baseToken?.name||"").toLowerCase();let flags=[];const hard=["wrapped","bridged","wormhole","test","fake","scam","rug","porn","sex"];const stable=["weth","wbtc","usdt","usdc","busd","dai","wsol","wbnb"];if(stable.includes(s))flags.push("stable/wrapped");if(hard.some(x=>s.includes(x)||n.includes(x)))flags.push("bad word");if(sector!=="meme"&&["inu","doge","dog","cat","pepe","shib","floki","bonk"].some(x=>s.includes(x)||n.includes(x)))flags.push("meme-style name");return flags}
function sectorMatch(p,sector,quality){if(sector==="auto"||quality==="soft")return true;const text=(String(p.baseToken?.name||"")+" "+String(p.baseToken?.symbol||"")+" "+String(p.url||"")+" "+String(p.dexId||"")).toLowerCase();return (TERMS[sector]||[]).some(t=>text.includes(t.toLowerCase()))}
function ageDays(p){const t=Number(p.pairCreatedAt||0);if(!t)return 0;return Math.max(0,Math.floor((Date.now()-t)/86400000))}
function keyToken(p){const chain=String(p.chainId).toLowerCase();const addr=String(p.baseToken?.address||"").toLowerCase();if(addr)return chain+":"+addr;const s=String(p.baseToken?.symbol||"").toLowerCase().replace(/[^a-z0-9]/g,"");const n=String(p.baseToken?.name||"").toLowerCase().replace(/[^a-z0-9]/g,"");return chain+":"+s+":"+n}
export default async function handler(req,res){res.setHeader("Access-Control-Allow-Origin","*");try{const chain=String(req.query.chain||"auto").toLowerCase();const sector=String(req.query.sector||"auto").toLowerCase();const depth=String(req.query.depth||"deep");const quality=String(req.query.quality||"soft");let queries=[...(TERMS[sector]||TERMS.auto)];if(sector==="auto")queries=TERMS.auto;if(depth==="normal")queries=queries.slice(0,6);if(depth==="deep")queries=queries.slice(0,14);let all=[];for(const q of queries){const r=await fetch("https://api.dexscreener.com/latest/dex/search?q="+encodeURIComponent(q));const j=await r.json();all.push(...(j.pairs||[]))}let best=new Map();for(const p of all){if(chain!=="auto"&&String(p.chainId).toLowerCase()!==chain)continue;const flags=flagsFor(p,sector,quality);if(quality==="strict"&&flags.length)continue;if(!sectorMatch(p,sector,quality))continue;const k=keyToken(p);
const nk=String(p.chainId).toLowerCase()+":name:"+String(p.baseToken?.symbol||"").toLowerCase().replace(/[^a-z0-9]/g,"")+":"+String(p.baseToken?.name||"").toLowerCase().replace(/[^a-z0-9]/g,"");
const raw=Number(p.liquidity?.usd||0)+Number(p.volume?.h24||0)/5;
const old=best.get(k)||best.get(nk);
if(!old||raw>old._rawScore){p._rawScore=raw;p._flags=flags;best.set(k,p);best.set(nk,p)}}let pairs=[...best.values()].map(p=>({id:String(p.chainId)+"-"+String(p.pairAddress),name:p.baseToken?.name||"Unknown",symbol:p.baseToken?.symbol||"?",image:p.info?.imageUrl||"",current_price:Number(p.priceUsd||0),market_cap:Number(p.marketCap||0),fdv:Number(p.fdv||0),total_volume:Number(p.volume?.h24||0),price_change_percentage_24h:Number(p.priceChange?.h24||0),_sector:sector,_source:"DexScreener",_dexChain:String(p.chainId).toLowerCase(),dex:p.dexId||"",pair:p.pairAddress||"",tokenAddress:p.baseToken?.address||"",baseAddress:p.baseToken?.address||"",liquidity:Number(p.liquidity?.usd||0),age_days:ageDays(p),flags:p._flags||[],url:p.url||"",website:(p.info?.websites&&p.info.websites[0]?.url)||""}));pairs.sort((a,b)=>(b.liquidity||0)+(b.total_volume||0)/5-((a.liquidity||0)+(a.total_volume||0)/5));res.status(200).json(pairs.slice(0,150))}catch(e){res.status(500).json({error:String(e.message||e)})}}